// File: C:\Users\nthorpe\Desktop\crm\idurar-erp-crm\frontend\src\redux\sponsors\actionTypes.js
export const FETCH_SPONSORS_REQUEST = 'FETCH_SPONSORS_REQUEST';
export const FETCH_SPONSORS_SUCCESS = 'FETCH_SPONSORS_SUCCESS';
export const FETCH_SPONSORS_FAILURE = 'FETCH_SPONSORS_FAILURE';
export const FETCH_SUMMARY_REQUEST = 'FETCH_SUMMARY_REQUEST';
export const FETCH_SUMMARY_SUCCESS = 'FETCH_SUMMARY_SUCCESS';
export const FETCH_SUMMARY_FAILURE = 'FETCH_SUMMARY_FAILURE';
export const ADD_SPONSOR_EVENT_SUCCESS = 'ADD_SPONSOR_EVENT_SUCCESS';
export const UPDATE_SPONSOR_TASK_SUCCESS = 'UPDATE_SPONSOR_TASK_SUCCESS';
export const SEND_SPONSOR_EMAIL_REQUEST = 'SEND_SPONSOR_EMAIL_REQUEST';
export const SEND_SPONSOR_EMAIL_SUCCESS = 'SEND_SPONSOR_EMAIL_SUCCESS';
export const SEND_SPONSOR_EMAIL_FAILURE = 'SEND_SPONSOR_EMAIL_FAILURE';
