// frontend/src/redux/sponsors/types.js
export const REQUEST_LOADING = 'SPONSORS_REQUEST_LOADING';
export const REQUEST_FAILED = 'SPONSORS_REQUEST_FAILED';
export const LOAD_SPONSORS_SUCCESS = 'SPONSORS_LOAD_SPONSORS_SUCCESS';
export const LOAD_SUMMARY_SUCCESS = 'SPONSORS_LOAD_SUMMARY_SUCCESS';
export const SEND_EMAIL_SUCCESS = 'SPONSORS_SEND_EMAIL_SUCCESS';
