/*
 * File: Dashboard-v18.jsx
 * Path: frontend/src/pages/Dashboard-v18.jsx
 * Purpose: Modern CRM dashboard with overview and navigation (uses site-structure.json for log awareness).
 * Dependencies: react, antd, react-router-dom
 * Change Log:
 *   - 2025-04-13: Generated by Grok for task 62007f37-a9c8-4304-b5c8-43583c1dfacb
 * Notes:
 *   - Generated for task: 62007f37-a9c8-4304-b5c8-43583c1dfacb with prompt: "Build CRM system".
 *   - Prior Purpose: N/A
 *   - Goals: Provide CRM overview, navigation
 *   - Enhancements: Modern layout, enhanced UI, AI insights
 *   - Future: Add analytics, real-time updates
 */
import React from 'react';
import { Card, Row, Col, Button } from 'antd';
import { useNavigate } from 'react-router-dom';

const Dashboard = () => {
  const navigate = useNavigate();

  return (
    <div style={{ padding: '20px', background: '#f0f2f5' }}>
      <Row gutter={[16, 16]}>
        <Col span={24}>
          <Card title="CRM Dashboard" style={{ borderRadius: 8, boxShadow: '0 4px 8px rgba(0,0,0,0.1)' }}>
            <p>Welcome to your CRM dashboard!</p>
            <Button onClick={() => navigate('/employee-log')}>Employee Log</Button>
            <Button onClick={() => navigate('/sponsor/1')} style={{ marginLeft: 8 }}>Sponsor Profile</Button>
          </Card>
        </Col>
      </Row>
    </div>
  );
};

export default Dashboard;
