/*
 * File Path: C:\Users\nthorpe\Desktop\crm\idurar-erp-crm\frontend\src\pages\EmployeeLog-v870.jsx
 * Purpose: Employee log page with clock-in/out and payroll management for Allur Space Console.
 * Dependencies: react, antd
 * Notes:
 *   - Provides clock-in/out functionality for employees, enhancing time tracking.
 *   - Generated by Allur Space Console for seamless integration.
 * Change Log:
 *   - 04/08/2025: Added clock-in/out features (Chat Line 8200-ish).
 *     - Why: User requested advanced functionality (User input, 23:46 UTC).
 *     - How: Implemented state-managed clock-in/out with timestamp logging.
 *     - Test: Add employee, clock in/out, verify timestamps in table.
 */
import React, { useState } from 'react';
import { Table, Button, Input, Form, Space } from 'antd';

const EmployeeLog = () => {
  const [employees, setEmployees] = useState([]);
  const [form] = Form.useForm();

  const handleAddEmployee = (values) => {
    const newEmployee = { ...values, id: Date.now(), clockIn: null, clockOut: null };
    setEmployees([...employees, newEmployee]);
    form.resetFields();
  };

  const handleClockIn = (id) => {
    setEmployees(prev => prev.map(emp => emp.id === id ? { ...emp, clockIn: new Date().toLocaleString() } : emp));
  };

  const handleClockOut = (id) => {
    setEmployees(prev => prev.map(emp => emp.id === id ? { ...emp, clockOut: new Date().toLocaleString() } : emp));
  };

  return (
    <div>
      <h1>Employee Log</h1>
      <Form form={form} onFinish={handleAddEmployee}>
        <Form.Item name="name" label="Name"><Input /></Form.Item>
        <Form.Item name="payroll" label="Payroll"><Input type="number" /></Form.Item>
        <Button type="primary" htmlType="submit">Add Employee</Button>
      </Form>
      <Table dataSource={employees} columns={[
        { title: 'Name', dataIndex: 'name', key: 'name' },
        { title: 'Payroll', dataIndex: 'payroll', key: 'payroll' },
        { title: 'Clock In', dataIndex: 'clockIn', key: 'clockIn' },
        { title: 'Clock Out', dataIndex: 'clockOut', key: 'clockOut' },
        {
          title: 'Actions',
          key: 'actions',
          render: (_, record) => (
            <Space>
              <Button onClick={() => handleClockIn(record.id)} disabled={record.clockIn}>Clock In</Button>
              <Button onClick={() => handleClockOut(record.id)} disabled={!record.clockIn || record.clockOut}>Clock Out</Button>
            </Space>
          )
        }
      ]} />
    </div>
  );
};

export default EmployeeLog;
    