/*
 * File: AppRouter.jsx
 * Path: frontend/src/AppRouter.jsx
 * Purpose: Enhanced routing for CRM site, generated with system awareness.
 * Dependencies: react, react-router-dom
 * Change Log:
 *   - 04/08/2025: Generated by Grok with full CRM support
 */
import React from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import Login from './pages/Login';
import Dashboard from './pages/Dashboard';
import SponsorProfile from './pages/SponsorProfile';
import EmployeeLog from './pages/EmployeeLog';
import Settings from './pages/Settings';

const AppRouter = () => (
  <Router>
    <Routes>
      <Route path="/login" element={<Login />} />
      <Route path="/dashboard" element={<Dashboard />} />
      <Route path="/sponsor/:sponsorId" element={<SponsorProfile />} />
      <Route path="/employee-log" element={<EmployeeLog />} />
      <Route path="/settings" element={<Settings />} />
      <Route path="/" element={<Dashboard />} />
    </Routes>
  </Router>
);

export default AppRouter;
